build_release_task:
  windows_container:
    dockerfile: ci/windows/Dockerfile
    os_version: 2019
  env:
    matrix:
      - ALLEGRO_CONFIG: Release MD
      - ALLEGRO_CONFIG: Release MT
      - ALLEGRO_CONFIG: Debug MD
      - ALLEGRO_CONFIG: Debug MT
  build_script: >
    "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86 &&
    pushd build\vs2015 &&
    msbuild ALLEGRO.sln /p:PlatformToolset=v140 /p:Configuration="%ALLEGRO_CONFIG%" /p:Platform=Win32 /maxcpucount /nologo
