language: c
compiler:
  - gcc
addons:
  apt:
    packages:
      - cmake
      - libasound2-dev
      - libjack-dev
      - libsdl2-dev
script:
- mkdir build-liballegro
- cd build-liballegro
- cmake -DCMAKE_BUILD_TYPE=Debug ..
- make
- tar -zcf lib-allegro.tar.gz include/ lib/
deploy:
  provider: releases
  skip_cleanup: true
  api_key: $GITHUB_TOKEN
  file: lib-allegro.tar.gz
  on:
    tags: true
