version: "{build}"
image: Visual Studio 2017
platform:
 - Win32

configuration:
 - Debug MD
 - Debug MT
 - Release MD
 - Release MT

branches:
  only:
    - allegro-4.4.2-agspatch

before_build:
  - ps: $Env:PLATFORM_TOOLSET="v141"

build:
  project: build/VS2015/ALLEGRO.sln
  parallel: true
  verbosity: minimal
  
artifacts:
  - path: build\VS2015\lib\alleg-debug-static.lib
    name: alleg-debug-static.lib
  - path: build\VS2015\lib\alleg-debug-static-mt.lib
    name: alleg-debug-static-mt.lib
  - path: build\VS2015\lib\alleg-static.lib
    name: alleg-static.lib
  - path: build\VS2015\lib\alleg-static-mt.lib
    name: alleg-static-mt.lib
